#!/bin/sh

directory=$1
name=$2
prefix=$(echo "${name}" | tr -d 'a-z')

enum="  "
decl=""
init="  "
count=0

for i in ${directory}/*.c ; do
  type=$(grep "@@TYPE@@" $i | sed "s/.*@@TYPE@@ *//")
  cats=$(grep "@@EXPORT@@" $i | sed "s/.*@@EXPORT@@ *//")
  doc=$(grep "@@DOC@@" $i | sed "s/.*@@DOC@@ */          /")
  enum="${enum}
  ${prefix}T_${type} = ${count}, /**<
  $doc */"
  init="${init}Action${type}_register((set) + ${prefix}T_${type}); \\
  "
  count=$((count + 1))
  decl="${decl}
/** Register ${type}
 */
${name}Registerer Action${type}_register;
"
  for cat in ${cats} ; do
    decl="${decl}/** ${cat} ${type}
 */
"
    [ "$cat" = "perform" ]  && decl="${decl}ActionPerformer Action${type}_perform;"
    [ "$cat" = "write" ]    && decl="${decl}ActionWriter    Action${type}_write;"
    [ "$cat" = "match" ]    && decl="${decl}ActionMatcher   Action${type}_match;"
    [ "$cat" = "argument" ] && decl="${decl}ParserElement   Action${type}_argument;"
    [ "$cat" = "close" ]    && decl="${decl}ActionCloser    Action${type}_close;"
    decl="${decl}
"
  done
done

cat << EOF
/* This file is automatically generated from the contents
 * of the "${directory}" directory
 */

#ifndef _AUTO_${name}_H_
#define _AUTO_${name}_H_

/** @defgroup ${name} Action ${directory}
 *
 * Automatically generated list of ${name}. @{
 */

/** List ${name} types.
 */
enum ${name}Type {
$enum
  ${prefix}T_Number = ${count}   /**< Number of ${name}Type */
};

$decl

/** Macro to run to register all the ${name}
 *
 * @param set The definition set to initialize.
 */
#define BUILD_INIT_${prefix}(set) \\
$init

/** @} */

#endif
EOF
